server:
  port: 9090
jwt:
  secret: "493358340235739058340598340598340598340598340598"
spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/v3/api-docs

        - id: productos-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/productos,/api/v1/productos/**
          filters:
            - AuthenticationFilter

        - id: inventario-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/inventarios,/api/v1/inventarios/**
          filters:
            - AuthenticationFilter

        - id: venta-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/ventas,/api/v1/ventas/**
          filters:
            - AuthenticationFilter

        - id: clientes-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/v1/clientes,/api/v1/clientes/**
          filters:
            - AuthenticationFilter

        - id: usuarios-service
          uri: http://localhost:8086
          predicates:
            - Path=/api/v1/usuarios,/api/v1/usuarios/**
          filters:
            - AuthenticationFilter
        
        - id: pago-service
          uri: http://localhost:8091
          predicates:
            - Path=/api/v1/pagos,/api/v1/pagos/**
          filters:
            - AuthenticationFilter

        - id: promocion-service
          uri: http://localhost:8092
          predicates:
            - Path=/api/v1/promocion,/api/v1/promocion/**
          filters:
            - AuthenticationFilter

        - id: carrito-service
          uri: http://localhost:8093
          predicates:
            - Path=/api/v1/carrito,/api/v1/carrito/**
          filters:
            - AuthenticationFilter

        - id: notificacion-service
          uri: http://localhost:8094
          predicates:
            - Path=/api/v1/notificacion,/api/v1/notificacion/**
          filters:
            - AuthenticationFilter

        - id: envios-service
          uri: http://localhost:8095
          predicates:
            - Path=/api/v1/envios,/api/v1/envios/**
          filters:
            - AuthenticationFilter

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: "Servicio Productos"
        url: /api/v1/productos/v3/api-docs
      - name: "Servicio Inventario"
        url: /api/v1/inventarios/v3/api-docs
      - name: "Servicio Clientes"
        url: /api/v1/clientes/v3/api-docs
      - name: "Servicio Carrito"
        url: /api/v1/carrito/v3/api-docs
      - name: "Servicio Ventas"
        url: /api/v1/ventas/v3/api-docs
      - name: "Servicio Pago"
        url: /api/v1/pagos/v3/api-docs
      - name: "Servicio Envios"
        url: /api/v1/envios/v3/api-docs
      - name: "Servicio Notificacion"
        url: /api/v1/notificacion/v3/api-docs
      - name: "Servicio Usuarios"
        url: /api/v1/usuarios/v3/api-docs
      - name: "Servicio Promocion"
        url: /api/v1/promocion/v3/api-docs
      - name: "Service Auth"
        url: /v3/api-docs
    

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG