spring.application.name=service-venta
server.port=8084

spring.datasource.url=jdbc:mysql://localhost:3306/db_venta_sunnydream?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

inventario.url=http://localhost:8083/api/v1/inventarios